# *WARNING* Do not change this file as it may break your notebooks

import os
os.environ['HOME'] = '/home/54f88798-4f73-4243-9cef-9e16f976d9ff'
os.environ['LC_CTYPE'] = 'en_US.utf-8'
os.environ['JAVA_HOME'] = '/usr/lib/jvm/default-java'
os.environ['TERM'] = 'xterm-256color'
os.environ['PYTHONSTARTUP'] = '/home/54f88798-4f73-4243-9cef-9e16f976d9ff/.pythonstartup.py'
os.environ['PYTHONANYWHERE_DOMAIN'] = 'anacondaapps.cloud'
os.environ['PYTHONANYWHERE_SITE'] = 'nb.anaconda.com'
os.environ['ANACONDA_API_DOMAIN'] = 'anaconda.com'
os.environ['ANACONDA_API_URL'] = 'https://anaconda.com/api'
os.environ['ANACONDA_APP_URL'] = 'https://anaconda.com/app'
os.environ['ANACONDA_ASSISTANT_API_URL'] = 'https://anaconda.com/api/assistant'
os.environ['ANACONDA_ASSISTANT_ENVIRONMENT_TYPE'] = 'cloud-notebooks-prod'
os.environ['ANACONDA_AUTH_DOMAIN'] = 'anaconda.com'
os.environ['ANACONDA_IAM_URL'] = 'https://anaconda.com/api/iam'
os.environ['ANACONDA_LEARNING_URL'] = 'https://learning.anaconda.com'
os.environ['ANACONDA_NOTEBOOKS_URL'] = 'https://nb.anaconda.com'
os.environ['ANACONDA_PROJECTS_DIR'] = 'anaconda_projects'
os.environ['http_proxy'] = 'http://proxy.server:3128'
os.environ['https_proxy'] = 'http://proxy.server:3128'
os.environ['no_proxy'] = 'localhost,127.0.0.1,localaddress,.localdomain.com,/var/run/docker.sock'
os.environ['API_TOKEN'] = '6f2ebd768a11e5868712aad2c382d1cbbeacfc60'
